// react/my-first-app/src/Badge.js
import React, {useState} from 'react'
function Badge(props){
//state can change , props do not

const [count, setCount] = useState(0)

const increment = () => {
    console.log('click event fired')
    setCount(count + 1);
}

    return (
        <button type="button" className="btn btn-primary" onClick={increment}>
    {props.caption} <span className="badge text-bg-secondary">{count}</span>
        </button>
    )
}
export default Badge;

// angular/my-first-app/src/app/badge.component.ts
import { Component, Input } from '@angular/core';

@Component({
    selector: 'app-badge',
    templateUrl: './badge.component.html' 
})
export class BadgeComponent{
    @Input('caption')title: string = "Default"
    count: number = 0

    incrementCount(){
        console.log('incrementing..');
        
      this.count++
    }
}
<button type="button" (click)="incrementCount()" class="btn btn-primary">
    {{title}} <span  class="badge text-bg-secondary">{{count}}</span>
  </button>
