// angular/my-first-app/src/app/dropdown/dropdown.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-dropdown',
  templateUrl: './dropdown.component.html',
  styleUrls: ['./dropdown.component.css']
})
export class DropdownComponent implements OnInit {

  show: boolean = false;

  toggleShow(){
    this.show = !this.show;
  }
  constructor() { }

  ngOnInit(): void {
  }

}

<div class="dropdown">
    <button (click)="toggleShow()" class="btn btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
      Dropdown button
    </button>
    <ul [ngClass]="show?'dropdown-menu show':'dropdown-menu'">
      <li><a class="dropdown-item" href="#">Action</a></li>
      <li><a class="dropdown-item" href="#">Another action</a></li>
      <li><a class="dropdown-item" href="#">Something else here</a></li>
    </ul>
  </div>

// react/my-first-app/src/Dropdown.js
import React, { useState } from 'react'

export default function Dropdown() {

    const [cuisines, setCuisines] = useState([
        "Mexican", "Japanese", "Indian", "Malay"
    ])
    const [show, setShow] = useState(false)
    const [caption, setCaption] = useState('Select cuisine')

    const toggleShow = () =>{
        setShow(!show)
    }
    const changeCaption = (cuisine) =>{
        setCaption(cuisine)
        setShow(false);
    }

  let cuisineList =  cuisines.map((cuisine, i)=> <li><a className="dropdown-item" href="#" onClick={()=>changeCaption(cuisine)}>{cuisine}</a></li>)
  return (
    <div className="dropdown">
  <button onClick={toggleShow} className="btn btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
    {caption}
  </button>
  <ul className={show?'dropdown-menu show': 'dropdown-menu'}>
    {cuisineList}
  </ul>
</div>
  )
}
