// angular/my-first-app/src/app/add-employee/add-employee.component.ts
import { Component, OnInit } from '@angular/core';
import { EmployeeService } from '../employee.service';
import { Employee } from '../view-employees/employee';

@Component({
  selector: 'app-add-employee',
  templateUrl: './add-employee.component.html',
  styleUrls: ['./add-employee.component.css']
})
export class AddEmployeeComponent implements OnInit {



  addEmployee(name: string, salary: string){
    console.log('Adding employee... ', {name, salary})
    this.employeeService.addEmployee({ name, salary: parseInt(salary)});
    console.log(this.employeeService.employees);
    
  }
  constructor(public employeeService: EmployeeService) { }

  ngOnInit(): void {
  }

}

<div class="input-group mb-3">
    <span class="input-group-text" id="basic-addon1">Name</span>
    <input #name (keyup)="0" type="text"  class="form-control" placeholder="Enter name" aria-label="Username" aria-describedby="basic-addon1" />
</div>
<div class="input-group mb-3">
    <span class="input-group-text" id="basic-addon1">Salary</span>
    <input #salary (keyup)="0" type="number"  class="form-control" placeholder="Enter salary" aria-label="Username" aria-describedby="basic-addon1" />
</div>
<div class="input-group mb-3">
   <button (click)="addEmployee(name.value, salary.value)" class='btn btn-primary'>Add Employee</button>
</div>

// react/my-redux-app/src/components/AddEmployee.js
import React, {useState} from 'react'

export default function AddEmployee() {
    const [name, setName] = useState('')
    const [salary, setSalary] = useState()

    const handleNameChange = (e) => {
        console.log('Change event.. ', e.target.value)
        setName(e.target.value)
    }
    const addEmployee = () => {
        console.log('Add employee.. ', name , salary)
    }

    return (
        <>
            <div className="input-group mb-3">
                <span className="input-group-text" id="basic-addon1">Name</span>
                <input type="text" value={name} onChange={handleNameChange} className="form-control" placeholder="Enter name" aria-label="Username" aria-describedby="basic-addon1" />
            </div>
            <div className="input-group mb-3">
                <span className="input-group-text" id="basic-addon1">Salary</span>
                <input type="number" value={salary} onChange={(e) => setSalary(e.target.value)} className="form-control" placeholder="Enter salary" aria-label="Username" aria-describedby="basic-addon1" />
            </div>
            <div className="input-group mb-3">
                <button onClick={addEmployee} className='btn btn-primary'>Add Employee</button>
            </div>
        </>


    )
}
