// angular/my-first-app/src/app/view-employees/view-employees.component.ts
import { Component, OnInit } from '@angular/core';
import { Employee } from './employee';

@Component({
  selector: 'app-view-employees',
  templateUrl: './view-employees.component.html',
  styleUrls: ['./view-employees.component.css']
})
export class ViewEmployeesComponent implements OnInit {

  employees: Array<Employee> = [
    {id: 2, name: 'Priya', salary: 34343},
    {id: 34, name: 'Rahul', salary: 43433}
  ];

  constructor() { }

  ngOnInit(): void {
  }

}

<table class="table">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">First</th>
        <th scope="col">Last</th>
        <th scope="col">Handle</th>
      </tr>
    </thead>
    <tbody>
      <tr *ngFor="let employee of employees">
        <th scope="row">{{employee.id}}</th>
        <td>{{employee.name}}</td>
        <td>{{employee.salary}}</td>
        <td>@mdo</td>
      </tr>
      
    </tbody>
  </table>

// react/my-redux-app/src/components/ViewEmployees.js
import React, {useState, useEffect} from 'react'

export default function ViewEmployees() {

  const [employees, setEmployees] = useState([{id: 1, name: 'Name1', salary: 99999}])
 

  const deleteEmployee = (id) => {
    let fileteredEmployees = employees.filter((employee)=>employee.id != id)
    setEmployees(fileteredEmployees)
  }

  let employeeList = employees.map((employee)=> {
    return (
        <tr key={employee.id}>
      <th scope="row">{employee.id}</th>
      <td>{employee.name}</td>
      <td>{employee.salary}</td>
      <td><button onClick={()=>deleteEmployee(employee.id)} className='btn btn-danger'> X </button></td>
    </tr>
    )
  })
  
    
  return (
    <table className="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Name</th>
      <th scope="col">Salary</th>
      <th scope="col">Handle</th>
    </tr>
  </thead>
  <tbody>
    {employeeList}
  </tbody>
</table>
  )
}
