// angular/my-first-app/src/app/update-employee/update-employee.component.ts
import { Component, OnInit } from '@angular/core';
import { EmployeeService } from '../employee.service';
import { ActivatedRoute } from '@angular/router';

import { Observable } from 'rxjs';
import { switchMap } from 'rxjs/operators';

@Component({
  selector: 'app-update-employee',
  templateUrl: './update-employee.component.html',
  styleUrls: ['./update-employee.component.css']
})
export class UpdateEmployeeComponent implements OnInit {
  empname: string = ''
  empsalary: string = ''
  message: string = ''

  updateEmployee(name: string, salary: string) {
    console.log('updating employee... ', { name, salary })
    this.employeeService.updateEmployee(this.route.snapshot.paramMap.get('id'), salary);
    this.message = "Successfully updated employee!"
    console.log(this.employeeService.employees);

  }
  constructor(public employeeService: EmployeeService, private route: ActivatedRoute) { }

  ngOnInit(): void {
    const employeeId = this.route.snapshot.paramMap.get('id');
    console.log('Employee id ', employeeId);
    this.employeeService.fetchEmployee(employeeId)
      .subscribe((res: any) => {
        console.log(res)
        this.empname = res.name
        this.empsalary = res.salary
      })



  }

}

<div *ngIf="message" class="alert alert-success" role="alert">
    {{message}}
  </div>

<div class="input-group mb-3">
    <span class="input-group-text" id="basic-addon1">Name</span>
    <input disabled="true" [value]="empname" #name (keyup)="0" type="text"  class="form-control" placeholder="Enter name" aria-label="Username" aria-describedby="basic-addon1" />
</div>
<div class="input-group mb-3">
    <span class="input-group-text" id="basic-addon1">Salary</span>
    <input  [value]="empsalary" #salary (keyup)="0" type="number"  class="form-control" placeholder="Enter salary" aria-label="Username" aria-describedby="basic-addon1" />
</div>
<div class="input-group mb-3">
   <button (click)="updateEmployee(name.value, salary.value)" class='btn btn-primary'>Update Employee</button>
</div>

// react/my-spa-app/src/components/UpdateEmployee.js
import React, {useState, useEffect} from 'react'
import { useParams } from 'react-router-dom';

export default function UpdateEmployee() {
    const [name, setName] = useState('')
    const [message, setMessage] = useState('')
    const [salary, setSalary] = useState()
    let params = useParams();

    console.log('update employee with id', params.id);


    useEffect(() => {
        fetch('http://localhost:8000/employees/' + params.id)
        .then(res=>res.json())
        .then((data)=> {
            console.log(data)
            setName(data.name)
            setSalary(data.salary)
        })
    }, [])
    

    const handleNameChange = (e) => {
        console.log('Change event.. ', e.target.value)
        setName(e.target.value)
    }
    const updateEmployee = () => {
        console.log('Add employee.. ', name , salary)
        //http post
        fetch('http://localhost:8000/employees/' + params.id, {
            method: 'PATCH',
            headers: {
                'Content-type': 'application/json'
            },
            body: JSON.stringify({salary})
        })
        .then(res =>{
            console.log(res);
            if(res.status == 201){
                setMessage('Employee updated successfully!')
            }
        })
      
    }
    return (
        <div>
            {message && <div class="alert alert-success" role="alert">
  {message}
</div>}
            
            <div className="input-group mb-3">
                <span className="input-group-text" id="basic-addon1">Name</span>
                <input  type="text" value={name} onChange={handleNameChange} className="form-control" placeholder="Enter name" disabled aria-label="Username" aria-describedby="basic-addon1" />
            </div>
            <div className="input-group mb-3">
                <span className="input-group-text" id="basic-addon1">Salary</span>
                <input  type="number" value={salary} onChange={(e)=>setSalary(e.target.value)} className="form-control" placeholder="Enter salary" aria-label="Username" aria-describedby="basic-addon1" />
            </div>
            <div className="input-group mb-3">
               <button onClick={updateEmployee} className='btn btn-primary'>Update Employee</button>
            </div>
        </div>
    )
}
